dist: trusty
language: cpp
compiler:
  - clang
  - gcc
script:
  - "./configure --debug --devel && make && CTEST_OUTPUT_ON_FAILURE=1 make test"
  - "./configure && make && CTEST_OUTPUT_ON_FAILURE=1 make test"
